Smithay/client-toolkit

Cargo.toml
examples/kbd_input.rs
examples/selection.rs
src/data_device/data_device.rs
src/data_device/data_offer.rs
src/data_device/data_source.rs
src/data_device/mod.rs
src/env.rs
src/lib.rs

basic data_device helpers

---

CHANGELOG.md

I remembered that I did not update the change log for key repetition https://github.com/Smithay/client-toolkit/pull/16

Update changelog for key repetition

---

.travis.yml

This PR fixes the travis rustfmt check.

Fix travis ci rustfmt check

---

CHANGELOG.md
README.md
examples/image_viewer.rs
src/lib.rs
src/surface.rs

Still need to do some more testing
Closes #44

WIP: Add surface abstraction.

---

examples/pointer_input.rs

Updates the pointer_input example. Relates to #47 
So figured out what needs to happen for #47. It looks like we can set_buffer_scale(max_dpi_of_all_outputs) and load the cursor theme when we get a GlobalEvent::New or GlobalEvent::Removed and let the compositor downscale the cursor when on a lowdpi screen.

Pointer dpi example

---

src/window/basic_frame.rs
src/window/concept_frame.rs

Fixes issue https://github.com/Smithay/client-toolkit/issues/54

Fix build error on big-endian targets

---

CHANGELOG.md
Cargo.toml
examples/image_viewer.rs
examples/kbd_input.rs
examples/pointer_input.rs
examples/selection.rs
src/data_device/data_device.rs
src/data_device/data_offer.rs
src/data_device/data_source.rs
src/env.rs
src/keyboard/mod.rs
src/output.rs
src/pointer/mod.rs
src/pointer/theme.rs
src/shell/mod.rs
src/shell/wl.rs
src/shell/xdg.rs
src/shell/zxdg.rs
src/surface.rs
src/utils/mempool.rs
src/window/basic_frame.rs
src/window/concept_frame.rs
src/window/mod.rs

This also includes a large refactor of the keyboard module to take advantage of the new API

Update to wayland-rs 0.22

---

src/lib.rs

Fix typos in `default_environment!` macro docs

---

CHANGELOG.md
src/surface.rs
src/window/concept_frame.rs

I've also fixed an issue with most left-bottom most pixel in a different color and line separator not drawing.

HiDPI scaling for decorations

---

CHANGELOG.md
src/seat/pointer/theme.rs

For more see https://github.com/Smithay/client-toolkit/pull/97#issuecomment-583773503 .

Fix HiDPI cursor icon position

---

CHANGELOG.md
src/window/concept_frame.rs

Add HiDPI scaling for decorations

---

CHANGELOG.md
src/surface.rs

Fix deadlock in surface scale factor callback

---

src/window/mod.rs

Certain structures are `!Send` + `!Sync` or could only
be accessed from `!Send` + `!Sync` data, meaning that
commonly used `Arc<Mutex<T>>` structure could be replaced with
`Rc<RefCell<T>>`.
I'm not entirely sure about device manager related bits, but I don't see why it should be `Arc<Mutex<_>>` for inner state.

Reduce the use of Mutex

---

src/shm/mempool.rs

This prevents us from ever shrinking the file (which we never do) and lets the
wayland server skip configuring its SIGBUS handler when accessing our buffers.

Set F_SEAL_SHRINK on memfds we create

---

.cirrus.yml
Cargo.toml
src/window/concept_frame.rs

use fontconfig directly instead of andrew's in-house code

---

CHANGELOG.md
Cargo.toml
examples/kbd_input.rs
examples/layer_shell.rs
examples/selection.rs
src/data_device/offer.rs
src/event_loop.rs
src/seat/keyboard/mod.rs

Apologies for the formatting problems @vberger. I've got an auto-formatter running on the files and can't work out the correct `.rustfmt.toml` for the current code; do you mind sharing the settings please?

Upgrade calloop version to `0.7.2`

---

Cargo.toml
examples/selection.rs
src/data_device/mod.rs
src/data_device/offer.rs
src/event_loop.rs
src/output.rs
src/primary_selection/mod.rs
src/seat/keyboard/mod.rs
src/seat/keyboard/state.rs
src/shell/mod.rs
src/shm/mempool.rs

This PR updates calloop to v0.9.0 and fixes the remaining warnings and clippy errors

Update calloop to v0.9.0

---

src/environment.rs

better error message for unhandled events in roundtrip

---

src/seat/mod.rs

Trivial change, just waiting for CI

output: fix bug where new_seat is not called

---

examples/simple_window.rs
src/seat/mod.rs
src/seat/pointer.rs

The pointer implementation was not well designed when I first wrote it. As well as untested.
This is a much more well designed implementation that also handles some things I overlooked.

 pointer: refactor api and fix bugs (0.30) 

---

src/shm/pool/mod.rs
src/shm/pool/multi.rs

Improvements on the MultiPool.

Multipool (rebase)

---

Cargo.toml

Trivial, going to merge when CI says it builds.

0.30: update to new alpha and pin alpha version

---

examples/simple_layer.rs
examples/simple_window.rs
src/compositor.rs
src/seat/pointer.rs

- serials in PointerHandler
- create_region in CompositorState

0.30: Add two missing items

---

Cargo.toml
src/compositor.rs
src/lib.rs
src/output.rs
src/registry.rs
src/seat/keyboard/mod.rs
src/seat/mod.rs
src/seat/pointer.rs
src/seat/touch.rs
src/shell/layer/dispatch.rs
src/shell/layer/mod.rs
src/shell/mod.rs
src/shell/xdg/inner.rs
src/shell/xdg/mod.rs
src/shell/xdg/window/inner.rs
src/shell/xdg/window/mod.rs
src/shm/mod.rs
src/shm/pool/raw.rs

layer shell is temporarily disabled until wayland-protocols-wlr is published

update to beta.1

---

src/compositor.rs
src/seat/keyboard/mod.rs
src/seat/mod.rs
src/seat/pointer.rs
src/seat/touch.rs

Allow applications to store data attached to wayland objects in addition to the data that SCTK stores there.

Custom user data

---

.cirrus.yml
Cargo.toml
examples/list_outputs.rs
examples/list_shm_formats.rs
src/compositor.rs
src/output.rs
src/registry.rs
src/seat/keyboard/mod.rs
src/seat/mod.rs
src/seat/pointer.rs
src/seat/touch.rs
src/shell/layer/dispatch.rs
src/shell/xdg/inner.rs
src/shell/xdg/popup.rs
src/shell/xdg/window/inner.rs
src/shm/mod.rs

Pending on https://github.com/Smithay/wayland-rs/pull/518

WIP: update to future beta.8 release

---

src/output.rs

Currently `remove_global` `.release()`s every output but the removed one.
---
By the way, wouldn't it make more sense to first run the callback and then call `.release()` and remove it from the list of outputs? Because currently, as far as I am aware, there is no way to get the output name/id from `output_destroyed` callback.

output: fix how remove_global is handled

---

src/registry.rs

Expose the list of globals in RegistryState

---

examples/image_viewporter.rs

This demonstrates SimpleGlobal for a useful global.

example: image_viewporter

---

src/shell/layer/mod.rs
src/shell/xdg/window/mod.rs

This also adds some helpers for WindowConfigure to test if some state is set.

update some configure docs for window and layer surfaces

---

src/shell/layer/dispatch.rs
src/shell/layer/mod.rs
src/shell/xdg/window/inner.rs
src/shell/xdg/window/mod.rs

Rework layer surface and window around cyclic user data

---

examples/generic_list_seats.rs
examples/generic_simple_window.rs
src/compositor.rs
src/output.rs
src/registry.rs
src/seat/keyboard/mod.rs
src/seat/mod.rs
src/seat/pointer.rs
src/seat/touch.rs
src/shell/layer/mod.rs
src/shell/xdg/mod.rs
src/shell/xdg/popup.rs
src/shell/xdg/window/mod.rs
src/shm/mod.rs

This PR adds generic delegate macros to sctk. See https://github.com/wash2/client-toolkit/blob/master/examples/generic_list_seats.rs for an example.

generic delegate macros

---

src/output.rs

With `zxdg_output_v1::done` deprecated in version 3, both Smithay and Sway seem to send `wl_output::done` twice at the start here, once after populating `wl_output` parameters, and again after populating the xdg output. So `new_output()` is immediately followed by `update_output()`.
This defers calling `new_output()` until we've gotten at least one xdg output event, which seems to work. I can't think of a better way to do it.

output: Don't call `update_output` at start when xdg outputs are present

---

src/seat/keyboard/repeat.rs

The interval is in CHARACTERS per second.

keyboard: fix repeat interval

---

examples/simple_layer.rs

Now press esc can exit simple-layer event

feat: simple_layer use esc to exit

---

src/seat/keyboard/repeat.rs

--
Not sure how it happened, likely somehow messed up during rebase.

seat/keyboard: fix capability check

---

examples/simple_window.rs
src/seat/keyboard/mod.rs
src/seat/keyboard/repeat.rs

Refactors keyboard repetition closer to original 0.16 implementation and fixes #356

Refactor: Keyboard Repetition

---

examples/data_device.rs
src/data_device_manager/data_device.rs

This adds a missing method to DataDevice and improves the data device example.

add missing method to DataDevice and improve its example

---

CHANGELOG.md
Cargo.toml
examples/themed_window.rs
src/shell/xdg/fallback_frame.rs
src/shell/xdg/mod.rs
src/shell/xdg/window/inner.rs

First patch bumps wayland-csd-frame, which fixes https://github.com/Smithay/client-toolkit/pull/387
The second adds xdg_shell v6 support.

Wayland csd frame bump

---

CHANGELOG.md
Cargo.toml
examples/data_device.rs
examples/generic_simple_window.rs
examples/image_viewer.rs
examples/image_viewporter.rs
examples/relative_pointer.rs
examples/simple_layer.rs
examples/simple_window.rs
examples/themed_window.rs
examples/wgpu.rs
src/compositor.rs
src/output.rs

Wire up new events instead of using watcher on the output and also handle transform changes.

Add support for wl_compositor v6

---

src/compositor.rs
src/seat/pointer/mod.rs
src/seat/touch.rs
src/subcompositor.rs

This is suitable for inclusion in a 0.18.1 release.

Macro build fixes

---

examples/data_device.rs
examples/generic_simple_window.rs
examples/simple_layer.rs
examples/simple_window.rs
examples/themed_window.rs
src/seat/keyboard/mod.rs

This is useful for passthrough compositors in combination with https://github.com/Smithay/smithay/pull/1218 and https://github.com/Smithay/smithay/pull/1221.

pass layout to update_modifiers

---

examples/data_device.rs
src/data_device_manager/data_device.rs

no data offer is included for internal DnD operations, so event handlers have no way of accessing the position and surface

fix: internal DnD event handlers need position and surface

---

examples/data_device.rs

I modified the example to help debug compositor drag surfaces. But it also seems clearerer that a drag operation is occuring when there's a drag surface (and this better demonstrates how the API is normally used.)

example/data_device: Show a simple drag surface
