- Cargo.toml
Nix 0.10.0 does not work on OpenBSD, but 0.11.0 does.
Signed-off-by: Gregor Best <gbe@unobtanium.de>
> Fix build on OpenBSD

- CHANGELOG.md
- src/window/basic_frame.rs
- src/window/mod.rs
I think that following the lead of GTK, QT..etc borders around windows should not be rendered as it uses up screen space and can look ugly. 
This pull request changes the drawing of the decorations so that the sides and bottom borders become invisible (it doesn't remove them because they are needed for window resizing). 
DECORATION_SIZE now controls how far away your mouse can be from the window to resize it (warning that it still plays a part in the positioning of buttons though)
Because of the adjustments to window geometry which is calculated with headless_geometry() the compositor can snap the inner surface to the sides of the screen and show it correctly in the gnome activities view
Full screen works without borders as you would expect any other window to do
I've also tested that it …
> Remove borders from windows

- src/window/basic_frame.rs
* Added a header bar part to basic frame and made top a border piece above the header bar for resizing
* Change the way the buttons are laid out so that changes to the HEADER_SIZE (DECORATION_TOP_SIZE) or BORDER_SIZE (DECORATION_SIZE) don't effect their layout
* Rename DECORATION_SIZE and DECORATION_TOP_SIZE as they are very similar, long and slightly unclear
* Border size is set to 12 to match the similar distance that gtk has
* I ran a cargo fmt just on basic_frame.rs
* The header bar size and border size can now be any value without unintended effect to the window (they can be set instead of const if wanted)
* The header bar can be better and properly sized from the top at all header bar sizes
I wasn't sure whether this was changelog worthy so I didn't add it but these changes do …
> Seperate header bar and top border

- CHANGELOG.md
- src/window/basic_frame.rs
* Window corners are rounded by calculating circle_width (X) from y and also ROUNDING_SIZE which sets the radius.
- diagram
* Windows look more standard as gtk, qt and x11 also round their windows by default
* The const ROUNDING_SIZE can be used to set the amount of rounding, I found that without shading 3 works best however once shading is done it will probably increase to 4-8 like gtk.
* Corners can look slightly pixelated as I have yet to try and implement window shading.
* At a ROUNDING_SIZE of higher than 3 the window doesn't fit nicely in the corners of mutter (should be fixed with shading).
* The calculation of circle_width could be cached instead of recalculated on every redraw however all redraw calculations aren't cached I think.
I think both the rounded and 'boxy' style look …
> Round window corners

- .travis.yml
- README.md
The update of tempfile 3.0.3 bumps rand to 0.5 which means that the client toolkit won't compile on rust 1.20. This pull request shows that the minimum rust version needed to compile the client toolkit is rust 1.22.
> Bump minimum rust version

- Cargo.toml
- examples/compositor_info.rs
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/selection.rs
- src/data_device/data_device.rs
- src/env.rs
- src/window/mod.rs
- src/window/shell/mod.rs
- src/window/shell/wl.rs
- src/window/shell/xdg.rs
- src/window/shell/zxdg.rs
fixes #1 
It only work with the `xdg-decorations`, which works with the stage `xdg-shell` protocol.
Not sure if there is already a compositor implementing both for testing...
> Server decorations

- src/window/basic_frame.rs
This pull request fixes subtraction overflow when calling find_button in basic_frame. This is a fatal issue as it crashes the program when the cursor is hovered over the button area when the window is too small for buttons to be drawn.
> Fix find_button to avoid subtraction overflow

- CHANGELOG.md
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/selection.rs
- src/utils/mempool.rs
- src/window/basic_frame.rs
This pull request makes it so that buffers aren't destroyed when they are in use by the server. Inactive buffer proxies (buffers not in the current memory pool) are stored in a vec so that they can destroyed if another redraw is called before the buffers can be swapped. All active buffers must be released before a mempool swap can occur. Please note that this code is based on my understanding that release events will only be sent to buffers in the current memory pool.
> Only destroy buffers when not in use

- src/env.rs
- src/keyboard/ffi.rs
- src/keyboard/mod.rs
- src/pointer/theme.rs
- src/utils/mempool.rs
- src/window/basic_frame.rs
- src/window/mod.rs
This PR fixes some of the 'reasonable' clippy issues. It fixes quite a few clippy lints however I left a few out because they were either irrelevant or unreasonable, for example passing a reference to a proxy and shortening arguments to functions, etc.
Heres a list of general clippy issues it fixes
* use `if lets` over `match`
* removal of \`static from consts (which are already static) - `&'static [u8] -> &[u8]`
* shorten argument passing - `some_arg: some_arg -> some_arg`
* removal of redundant returns - `return Err() -> Err()`
* removal of `clone()` for objects with Copy
* check if result `is_ok()` instead of matching - `match result -> if result.is_ok()`
* space out numbers - `1000000 -> 1_000_000`
* use AtomicBool over Arc<Mutex<bool>>
* pass reference instead of object
* use …
> Fix reasonable clippy lints

- CHANGELOG.md
- src/keyboard/mod.rs
This PR ends key repetition when the keyboard loses focus as the release event will never be sent in these cases. When the keyboard loses focus it just ends the key repetition and doesn't send a release event as the key isn't actually released (in the physical sense) I can change this behavior if you want.
> End key repetition when keyboard loses focus

- CHANGELOG.md
- Cargo.toml
- examples/compositor_info.rs
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/selection.rs
- src/data_device/data_device.rs
- src/data_device/data_offer.rs
- src/data_device/data_source.rs
- src/env.rs
- src/keyboard/mod.rs
- src/output.rs
- src/pointer/mod.rs
- src/pointer/theme.rs
- src/utils/mempool.rs
- src/window/basic_frame.rs
- src/window/mod.rs
- src/window/shell/mod.rs
- src/window/shell/wl.rs
- src/window/shell/xdg.rs
- src/window/shell/zxdg.rs
This PR upgrades the smithay-client-toolkit to use wayland-rs 0.21 (pure rust implementation :tada:)
This PR makes necessary breaking modifications to the API but I've tried to minimize the changes, the API can be changed to better fit wayland-rs 0.21 if you'd like. I've run this through clippy and tested the examples but I'll be porting winit to use this PR to test the changes in more depth as well as reading through the diff a bit more.
> Upgrade to wayland-rs 0.21

- CHANGELOG.md
- examples/kbd_input.rs
- src/keyboard/mod.rs
When a modifier key is pressed then the modifiers will not show that key as active, for example pressing the shift key will show shift as inactive in the `Event::Key { modifiers, .. }`, therefore a modifiers event allows access to modifiers even when that modifier is the key being pressed.
> Add `keyboard::Event::Modifiers`

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/utils/mempool.rs
- src/window/basic_frame.rs
I've done some work on moving the decoration drawing code to a new crate called andrew (the name is a play on 'drew' being the past tense of 'draw'). Currently the crate is quite basic with its only functionality being bresenham lines and bordered/rounded rectangles or squares. I hope to add some more geometric objects and effects before the 0.1 release, most important being circles, circular sectors, shadows and gradients. 
The current fork doesn't work yet as andrew isn't released but I can tell you that it looks the exact same as before. The main purpose of this pull request is so that the crate's api can be reviewed and reworked while its still in a non-release stage. I'll give a little explanation on the crates api so far.
The Draw trait which looks like this
```
pub trait Draw {
fn …
```
> Draw decorations using a seperate crate

- CHANGELOG.md
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/pointer_input.rs
- examples/selection.rs
- src/data_device/data_device.rs
- src/data_device/data_offer.rs
- src/data_device/data_source.rs
- src/keyboard/ffi.rs
- src/keyboard/mod.rs
- src/pointer/mod.rs
- src/pointer/theme.rs
- src/window/basic_frame.rs
- src/window/concept_frame.rs
I think its better to panic on functions that return results even if it doesn't matter too much if the function fails, or at least they should be printed to stderr to log the failure.
A few arguments can be passed more efficiently, proxies by reference probably don't save a lot performance wise but are more idiomatic and now's probably a good time to change these considering the next release will be breaking.
> Cleanup - Handle function errors, remove unnecessary assignment, pass arguments more efficiently

- CHANGELOG.md
- Cargo.toml
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/selection.rs
- src/window/basic_frame.rs
- src/window/concept_frame.rs
- src/window/mod.rs
This is a work in progress PR for titled windows. It currently uses rusttype and fontconfig-rs to draw text and select fonts.
This PR currently has some issues with the loading of '.otf' fonts (this seems to be to do with rusttype) as well as the use of font_loader which depends on fontconfig-rs meaning projects using both the client-toolkit and fontconfig-rs will get a cargo multiple native link error.
Are titled windows something you think would be nice to have BasicFrame support or do you think its too complex?
> Display title in the window header decoration

- src/window/basic_frame.rs
- src/window/concept_frame.rs
Decorations now need to be refreshed on `set_title()` because the window title is displayed in the header
> Request frame refresh on `set_title()`

- CHANGELOG.md
- src/window/basic_frame.rs
- src/window/concept_frame.rs
- src/window/mod.rs
The automatic triggering of a refresh after calling `set_title()` when also handling a window event causes a mutex deadlock. 
Requiring the user to manually refresh the window after setting the title fixes this issue.
I cannot find any other instances where this sort of deadlock would occur but would be happy to include them in this PR if there are.
Fixes https://github.com/Smithay/client-toolkit/issues/56
> Require a `refresh()` after `set_title()` for changes to take effect

- Cargo.toml
While wayland itself is not supported on OpenBSD (and probably never will be) Smithay/client-toolkit is a dependency of jwilm/alacritty even when wayland is not in use.
There is a new nix release which fixes a build issue on OpenBSD, please see below.
Also, would it be possible to do a version bump for Smithay/client-toolkit to 0.4.5 ? I can add the relevant commit in this PR if it's ok. This is so I can update the downstream dependency in alacritty.
```bash
user1 ~/ALACRITTY/client-toolkit $ cargo build
Updating crates.io index
Downloading crates ...
Downloaded wayland-client v0.21.4
Downloaded wayland-protocols v0.21.4
Downloaded wayland-commons v0.21.4
Downloaded xdg v2.1.0
Downloaded libc v0.2.47
Downloaded wayland-sys v0.21.4
Downloaded rusttype v0.7.2
Downloaded approx v0.3.0 …
```
> Update nix dependency to 0.13.0

- CHANGELOG.md
- src/keyboard/mod.rs
This was a mistake I made when implementing the key repetition. The delay should be milliseconds but the repeat rate is repeats per second.
```
from wayland docs:
rate | the rate of repeating keys in characters per second
delay | delay in milliseconds since key down until repeating starts
```
Thanks to @e00E for catching this bug
> Fix system repeat rate

- Cargo.toml
- src/window/basic_frame.rs
- src/window/concept_frame.rs
- src/window/mod.rs
Version 0.2.0 of andrew takes an `Endian` argument when creating the canvas which means that SCTK doesn't have to store both endian versions of colors.
> Update to andrew 0.2.0

- CHANGELOG.md
- src/shell/xdg.rs
- src/shell/zxdg.rs
Firing on xdg_toplevel_surface.configure is wrong: if the client
attaches as a response to the cb, the attach will reach the server
before the ack_configure, which is a protocol error.
> window: fire user cb on xdg_surface.configure

- Cargo.toml
This should probably be handled as a follow-up to https://github.com/Smithay/wayland-rs/pull/265
Once that is merged, I can update this to completely get rid of nix 0.13.
> Update to nix 0.14.1

- CHANGELOG.md
- src/keyboard/mod.rs
Fixes when a modifier release event occurs so a state change message is sent to the key repeat thread, thus making it so that the thread doesn't receive a disconnect message on `try_recv()`.
Fixes https://github.com/Smithay/client-toolkit/issues/73
> fix extra key repeat when also releasing a modifier

- src/window/concept_frame.rs
This happened (for me) when using alacritty on a wayland desktop. Seems
that there is some messed up font in the fontconfig list. Let's just
ignore these broken fonts.
> do not crash when fonts don't have extensions

- src/surface.rs
This implementation was erroneously not threadsafe, making it impossible to access the surface dpi from an other thread.
Will fix https://github.com/rust-windowing/winit/issues/1441
> surface: implementation should be threadsafe

- CHANGELOG.md
- src/window/mod.rs
SCTK by default uses SSD decorations, however `set_decorations` true,
could force it to draw decorations and unset_mode assuming it's SSD,
however compositor can change SSD to CSD, so this unset will fallback
back to SSD and it'll mess up inner state.
This commit makes `set_decorations` to hide/show decorations only in CSD
mode, in SSD mode it's up to server on what to do.
> Fix `set_decorations` arbitrary changing SSD mode to CSD

- CHANGELOG.md
- src/pointer/theme.rs
It seems like just porting the same code from 0.7.0 didn't work. While updating winit, I've noticed that cursor position reported is a bit different compared to shape. I don't quite get why this fixes the issue, however I think I should normalize thing?
I wonder why I can't notice it on v0.7.0 tbh, but maybe something was change internally?
> Fix HiDPI cursor icon position [backport]

- CHANGELOG.md
- examples/layer_shell.rs
- src/lib.rs
- src/output.rs
This function, available through the OutputHandling trait, makes it
possible to register a listener for the creation and removal of outputs.
This is as of yet untested as I wasn't quite sure what the best practice is there.  Should I just create a simple example using it?
> Implement listen_for_outputs

- CHANGELOG.md
- src/seat/mod.rs
It's a bit nicer way than doing something like.
```rust
if let Some(seat_data) = seat::with_seat_data(&seat, |seat_data| seat_data.clone()) {
}
```
So it should be just
```rust
if let Some(seat_data) = seat::seat_data(&seat) {
}
```
> Add `seat_data()` method as a shorthand to get `SeatData`

- src/surface.rs
Don't consider the output list becoming empty as a scale factor change,
to avoid unneeded transient changes between scale 1 and the real scale
factor when surface is hidden / shown.
This notably affects cursor surfaces, whose output list becomes empty as
soon as they leave the app surface on some compositors.
> surface: don't count being hidden as a DPI change

- src/seat/keyboard/ffi.rs
> remove unnecessary parentheses

- src/seat/keyboard/ffi.rs
- src/seat/keyboard/keysyms.rs
- src/seat/keyboard/mod.rs
It's either rust 1.44.0 broke old things entirely or removed them. Anyway, the new way is to skip formatting like that IIRC.
> chore: update rustfmt attributes

- CHANGELOG.md
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/layer_shell.rs
- examples/pointer_input.rs
- examples/selection.rs
- examples/themed_frame.rs
- src/surface.rs
- src/window/concept_frame.rs
We should return `Attached<WlSurface>` from `create_surface`
and `create_surface_with_scale_callback` to simplify handling
of frame callbacks and object creation, since queue could be
unavailable in a place of surface creation.
Fixes #132.
> surface: Return `Attached<WlSurface>` instead of WlSurface

- CHANGELOG.md
- src/seat/mod.rs
Some compositors(plasma) do use empty name for a seat name, filtering
out by empty seat name, was leading to not working clipboard on such
compositors.
> Advertise seats with an empty name

- CHANGELOG.md
- src/event_loop.rs
I actually need `queue_mut`, since I should do `sync_roundtrip` after creating a window in winit and dispatching also requires a mut EventQueue.
> event_loop: add WaylandSource::queue_mut()

- CHANGELOG.md
- src/shell/mod.rs
- src/shell/wl.rs
- src/shell/xdg.rs
- src/shell/zxdg.rs
- src/window/concept_frame.rs
- src/window/mod.rs
Some compositors like mutter can show window menu
when performing xdg_toplevel.show_mindow_menu.
That's how it looks on GNOME. (cursor is there, just wasn't captured by `grim`).
> Request window menu when right clicking on CSD decorations

- src/seat/keyboard/mod.rs
- src/seat/keyboard/state.rs
If the keymap is not passed to init_with_fd, the file descriptor is leaked.
Wrap the fd in a File earlier on so normal drop code takes care of this.
The virtual-kbd program at https://github.com/danieldg/wlroots/blob/master/examples/virtual-kbd.c triggers this leak, if you want to test.
> Fix fd leak in keymap updates

- CHANGELOG.md
- src/seat/keyboard/mod.rs
Milliseconds are not accurate enough resulting in lower
repeat gap than it should be, however using microseconds seems enough
to solve that.
Fixes #141.
> Fix precision in keyboard repeated keys events rate

- CHANGELOG.md
- src/window/mod.rs
This commit changes the behavior of how `window.set_decorate`
works in a following way.
If `zxdg_toplevel_decoration_v1` object is presented and alive,
requesting `None` decorations will result in setting `ClientSide`
decorations with hidden frame, and if `ClientSide` decorations were
requested, it'll result in destroying `zxdg_toplevel_decoration_v1`
object, meaning that you won't be able to get `ServerSide` decorations
back.
In case `zxdg_toplevel_decoration_v1` is not available or the
corresponding object is not alive anymore, `decorate` with `ServerSide`
or `FollowServer` values will always result in `ClientSide` decorations
being used.
Fixes #143.
> Rework window.set_decorate handling

- CHANGELOG.md
- src/window/concept_frame.rs
- src/window/mod.rs
In general there's no value in showing decorations for fullscreen
window. We also can't rely on users hidding them, since they should
manually recompute the size accounting for the decorations.
This commit also makes window to restore the size, which it had
before being fullscreened.
I've tested this on GNOME and weston with winit, and it works very good. I wonder whether we should document that concept frame isn't drawing decorations for fullscreen state?
> Hide decorationos in fullscreened ConceptFrame

- CHANGELOG.md
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/pointer_input.rs
- examples/selection.rs
- examples/themed_frame.rs
- src/seat/pointer/theme.rs
- src/window/concept_frame.rs
- src/window/mod.rs
Allow users to pass `ThemeManager` to reduce the usage of resources
and extra loads of users' themes.
Frames could use that to detect whether they should theme cursor
over the base surface.
> Add 'Option<ThemeManager>' argument to 'create_window'

- CHANGELOG.md
- src/seat/keyboard/mod.rs
Wayland spec says that zero rate in wl_keyboard.repeat_info means
that key repeat must be disabled.
Relevant spec part https://gitlab.freedesktop.org/wayland/wayland/-/blob/master/protocol/wayland.xml#L2283
> Disable key repeat when getting zero rate in repeat_info

- CHANGELOG.md
- src/window/mod.rs
Some compositors like GNOME tile you move your window into 'hot corners'.
Once you leave a hot corner they rely on you restoring your original size.
> Restore original window size after being tiled

- CHANGELOG.md
- src/window/concept_frame.rs
- src/window/mod.rs
Previously 'ConceptFrame' was always creating subsurfaces, which
was consuming unnecessary resources when ServerSide decorations were
used. Now it'll create those only when frame is in fact visible.
Tested on kwin(wayland) where it fixes https://bugs.kde.org/show_bug.cgi?id=419235 , however it's still a kwin bug.
gnome(wayland)
weston
sway.
> Create subsurfaces in 'ConceptFrame' only when needed

- src/output.rs
- src/seat/mod.rs
It makes more clear that the result from calling 'listen_for_seats'
and 'listen_for_outputs' must be kept around to keep the user's callback
alive.
Example of how it looks.
```
warning: unused return value of `sctk::seat::<impl sctk::environment::Environment<E>>::listen_for_seats` that must be used
--> examples/kbd_input.rs:105:5
|
105 | /     env.listen_for_seats(move |seat, seat_data, _| {
106 | |         // find the seat in the vec of seats, or insert it if it is unknown
107 | |         let idx = seats.iter().position(|(name, _)| name == &seat_data.name);
108 | |         let idx = idx.unwrap_or_else(|| {
...   |
140 | |         }
141 | |     });
| |_______^
|
= note: `#[warn(unused_must_use)]` on by default
= note: the returned SeatListener keeps your callback alive, dropping it will …
```
> Add 'must_use' annotations for listeners

- CHANGELOG.md
- examples/compositor_info.rs
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/layer_shell.rs
- examples/pointer_input.rs
- examples/selection.rs
- examples/themed_frame.rs
- src/environment.rs
- src/lib.rs
- src/output.rs
- src/shell/mod.rs
Previously 'Environment' was initialized via 'init' method,
and then it was requiring downstream to perform two sync roundtrips
to the server, which wasn't ergonomic for rust API, however the
initialization without two roundtrips could be preferred in some
scenarios.
This commit adds new method 'Environment::new', which will take
'EventQueue' and perform proper initialization for the users. The old
method is now named 'Environment::new_pending', and you'll still have
to perform two roundtrips.
In addition, this commit renames 'init_default_environment!' to
'new_default_environment!' to respect new naming scheme.
> Rework 'Environment' initialization methods

- Cargo.toml
- src/seat/keyboard/state.rs
- src/shm/mempool.rs
This pull request replaces the memmap dependency with the mapr crate in accordance with [this Rust security advisory](https://rustsec.org/advisories/RUSTSEC-2020-0077). I had at first proposed the memmap2 crate, but after seeing that the last release was from a year ago, switched to mapr. Closes #165.
This is my first time contributing to smithay-client-toolkit. Let me know if I need to do anything else.
Edit: Now replacing with memmap2 because of FreeBSD issues.
> Replace memmap with memmap2

- CHANGELOG.md
- Cargo.toml
- examples/image_viewer.rs
- examples/kbd_input.rs
- examples/layer_shell.rs
- examples/pointer_input.rs
- examples/selection.rs
- examples/themed_frame.rs
- src/seat/keyboard/mod.rs
- src/shell/xdg.rs
- src/shell/zxdg.rs
This PR removes the dependency on the byteorder crate.
My motivation is a bad one: Less dependencies! (and byteorder is not really necessary for the things that are done here)
My testing is weak: `cargo build --all-targets && cargo test` succeeds. I did not even run any of the examples since I do not have a wayland compositor at hand.
I did this in separate commits so that in case something is wrong, `git bisect` is more helpful. However, I am not sure if that is really necessary. If wanted, I can squash this.
> Remove byteorder dependency

- CHANGELOG.md
- src/window/mod.rs
As discussed in chat.
I have copied the documentation from the wayland-protocols specification, as I have basically very little clue about Wayland I'm open to suggestions, thank you.
~~I will leave it as a draft until I try it out, which I'm in the process of doing at the moment.~~
Tested with https://github.com/rust-windowing/winit/pull/1840, works like a charm.
> Implement `start_interactive_move`.

- CHANGELOG.md
- src/output.rs
This adds name and description fields to OutputInfo and populates them if a properly initialized XdgOutputHandler is present.  If the global is not present or not offered by the server, output handling is unchanged and the new fields will be blank.
> Add optional xdg_output support

- .github/workflows/ci.yml
- Cargo.toml
- src/seat/keyboard/ffi.rs
- src/seat/keyboard/state.rs
I am packaging a version of [alacritty](https://github.com/alacritty/alacritty) that runs on Wayland (without Xwayland) for [Guix](https://guix.gnu.org/), a distro which, like NixOS, stores all shared libraries in a [weird place](https://guix.gnu.org/manual/en/html_node/The-Store.html). The dynamic linker doesn't check this path by default, so sometimes packagers are forced to modify the library search path after building, but a better way is to link to the library at compile time.
This commit introduces a "dlopen" feature that is enabled by default that preserves the existing behavior of not linking to libxkbcommon except for trying to dlopen it at runtime. If the feature is disabled, cargo will link to the system's libxkbcommon.so at compile time.
To do this, I used the [generic macros …
> Allow linking to libxkbcommon at compile time

- CHANGELOG.md
- src/shm/mempool.rs
- src/shm/mod.rs
This tracks the allocation of regions in a MemPool along with the
Wayland server's release operations instead of requiring a callback to
notify the client that reuse is possible.
Note that even with the normal MemPool, clients should prefer using
wl_surface::frame to delay draw operations instead of using the SHM
release callback.
> Add an alternate AutoMemPool for allocating buffers

- Cargo.toml
This PR updates the memmap2 dependency to the latest version.
The change does not seem to require any actual code changes. Builds fine and all tests pass.
> Bump memmap2 to 0.3.0

- CHANGELOG.md
- src/shm/mempool.rs
This mostly already happens, but it is useful to guarantee it, especially if rendering directly to the shm canvas.
> Add minimum alignment guarantees to buffers from AutoMemPool

- CHANGELOG.md
- Cargo.toml
- build.rs
some OS (like OpenBSD or NetBSD) places third-parties libraries in no default paths, and requires explicit configuration to link to them. It makes smithay-client-toolkit difficult to build on such systems, as when not using `dlopen` feature, the build will fail.
For example, with alacritty build:
```
Building [=======================> ] 188/189: alacritty(bin)
error: linking with `cc` failed: exit status: 1
|
= note: [annoying stuff]
= note: ld: error: unable to find library -lxkbcommon
cc: error: linker command failed with exit code 1 (use -v to see invocation)
error: aborting due to previous error
error: could not compile `alacritty`
To learn more, run the command again with --verbose.
```
Currently, there is no way to specify a directory in smithay-client-toolkit to found the library …
> use pkg-config to properly link to xkbcommon library when build without dlopen feature

- CHANGELOG.md
- Cargo.toml
- src/event_loop.rs
Fixes #212
@Molytho can you confirm this one is correct for good?
> event_loop: correctly use prepare_read()

- src/seat/pointer.rs
Pointer abstractions do need testing, but are essentially complete. So this macro is being added to allow testing in smithay.
> pointer: add delegate_pointer macro

- examples/simple_window.rs
- src/compositor.rs
- src/shell/mod.rs
- src/shell/xdg/inner.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
This splits the windows out of `XdgShellState` and into a new `XdgWindowState`. This makes the xdg shell abstractions much more modular and removes the need to have `delgate_xdg_shell` require `delegate_xdg_window`.
> xdg-shell (0.30): split windowing out of XdgShellState

- examples/simple_window.rs
- src/shell/xdg/inner.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
Vast improvements to `Window` abstraction in xdg shell handling for SCTK.
Changes include:
- Moving configure to `WindowHandler`, each derivation of `XdgSurface` is expected to provide it's own handler method for configures.
- Window creation uses a builder
- Creating an XdgSurface, returned as a `XdgShellSurface` is now possible to allow external implementations of protocols which extend `XdgSurface`.
- Better server side decoration handling
- General cleanup of window data
> 0.30 xdg: idea to make configures better

- src/shell/xdg/window/mod.rs
Window isn't very usable in contexts where multiple exist without a way to identify a window
> 0.30: add missing PartialEq for window

- examples/simple_layer.rs
- src/shell/layer/dispatch.rs
- src/shell/layer/mod.rs
- src/shell/mod.rs
Shell abstractions for the layer shell. This is modeled off the xdg shell abstractions currently in 0.30.
We intentionally wrap types used by the wlr protocol since there is a future ext extension being proposed. We do not implement the ext extension (but it was considered during the design).
> 0.30: layer shell

- CHANGELOG.md
- src/window/mod.rs
Due to decorations manager not being destroyed, its callback was keeping
alive holding the reference to window's inner frame storage preventing
`wl_pointer`s from being released on drop.
That caused issue [1] downstream.
[1] - https://github.com/rust-windowing/winit/issues/2248
> Fix window's `wl_pointer` not releasing on drop

- src/data_device/device.rs
- src/data_device/offer.rs
This PR adds:
- a method to DataOffer which receives data to a raw file descriptor, then closes it.
- a method to DataDevice which gives access to the current DnD offer outside of a DnDEvent, which I've found useful.
I'm working on wrapping xdg windows with a layer shell window. One of the use cases I'd like to support is forwarding the clipboard contents into the embedded compositor inside the layer shell window. What I'm currently trying to do is:
1. set the compositor provided selection when the layer shell window gains keyboard focus for a seat. https://smithay.github.io/smithay/smithay/wayland/data_device/fn.set_data_device_selection.html
2. Wait for the SendSelection request in the callback I provided to init_data_device. https://docs.rs/smithay/latest/smithay/wayland/data_device/fn. …
> DataOffer low level receive method & DataDevice with_dnd method

- src/compositor.rs
- src/shm/mod.rs
Most RegistryHandlers expose their contained global; add it to Shm and Compositor.
> Expose globals via State objects

- src/compositor.rs
- src/error.rs
- src/lib.rs
- src/shell/layer/mod.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/mod.rs
- src/shm/mod.rs
- src/shm/pool/mod.rs
- src/shm/pool/raw.rs
Replace all the duplicate errors with one common error type.
> 0.30 replace XYZError::MissingGlobals with GlobalError

- examples/simple_layer.rs
- examples/simple_window.rs
- src/shm/mod.rs
- src/shm/pool/mod.rs
- src/shm/pool/raw.rs
- src/shm/pool/slot.rs
This provides an API based on dividing the pool into slots.  It is simpler than MultiPool because it does not move slots, which might result in more memory use if there are many resize operations.
> Port AutoMemPool to 0.30-rework

- Cargo.toml
- examples/simple_window.rs
- src/shell/layer/dispatch.rs
- src/shell/layer/mod.rs
- src/shell/mod.rs
- src/shell/xdg/inner.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
Beta 1 now allows per instance user data, so each xdg surface role should provide a delegate implementation for it's surface and type of data.
> remove generics on XdgShellState

- examples/simple_layer.rs
- examples/simple_window.rs
- src/seat/pointer.rs
This exposes all the events in a pointer frame in one user callback instead of making them distinct function calls.  It also provides tracking of the active surface and pointer position for all events, which is useful for button press/release.
Axis (scroll) events now correctly report both discrete and absolute distances, instead of just the first of the two that was reported.
> Simplify PointerHandler

- src/output.rs
This helps to populate name field when retrieving OutputInfo.
> bump: wl_output least supported version - 4

- .github/workflows/ci.yml
- README.md
- examples/layer_shell.rs
`Vec::retain_mut()` is stabilized in Rust 1.61
> layer_shell example: use Vec::retain_mut()

- src/shm/mod.rs
`ShmState` doesn't really need a `Registry` to function or to be created but currently, it's complicated if not impossible to use `ShmState` without the `Registry`.
This PR adds a `From<WlShm>` implementation to `ShmState` so it can be used without a `Registry`.
> Add From implementation to ShmState

- .github/workflows/ci.yml
- examples/image_viewer.rs
- src/compositor.rs
- src/globals.rs
- src/lib.rs
- src/output.rs
- src/registry.rs
- src/shell/layer/dispatch.rs
- src/shell/layer/mod.rs
- src/shell/xdg/inner.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/popup.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
- src/shm/mod.rs
- src/shm/pool/slot.rs
This allows decoupling users of globals from the `*State` types that bind them.
> Add ProvidesBoundGlobal trait

- src/compositor.rs
- src/globals.rs
- src/output.rs
- src/registry.rs
- src/shell/layer/dispatch.rs
- src/shell/xdg/inner.rs
- src/shell/xdg/window/inner.rs
- src/shm/mod.rs
People that don't commit fully to the SCTK can use GlobalData to satisfy trait implementations necessary to use other SCTK types.
> Make GlobalData fully public

- Cargo.toml
- examples/wgpu.rs
This effectively tests EGL and Vulkan with sctk.
Bump to 2021 was needed because wgpu requires `resolver = "2"`
> example: rendering with wgpu

- src/seat/keyboard/mod.rs
When using just wayland_client + KeyboardHandler, it is unnecessary for
the application's State to implement SeatHandler. It is, however,
necessary to implement KeyboardHandler when implementing SeatHandler.
> Don't require SeatHandler for KeyboardHandler

- Cargo.toml
- src/seat/keyboard/mod.rs
https://wayland.freedesktop.org/docs/html/apa.html
From version 7 onwards, the fd must be mapped with MAP_PRIVATE by the recipient, as MAP_SHARED may fail. 
Binding to version 7 seems to be the reason that simple_window example is panicking, and is referenced here https://github.com/rust-x-bindings/xkbcommon-rs/blob/8d237eedc345a110797cbe8edc515c09c098244b/src/xkb/mod.rs#L719
> Fix/ use xkbcommon git dependency

- src/seat/pointer.rs
- src/seat/touch.rs
This is essentially ee4ed37a8b789b891299af7822da8e0c3d2f1788 for PointerHandler and TouchHandler.
See: https://github.com/Smithay/client-toolkit/pull/289
> Don't require SeatHandler when unnecessary

- Cargo.toml
- src/output.rs
- src/registry.rs
- src/shell/layer/mod.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/mod.rs
- src/shm/slot.rs
1b2aaa92b701a8c04375ce0043b285ca4f2e39d6 is just to make `client-toolkit` build, since it won't build otherwise due to transitive dependencies. I can split that into a separate MR if that's preferring.
Other commits are probably best viewed individually, but they're all documentation tweaks (the one for `OutputState` also serves as a basic doctest too).
> Documentation improvements

- Cargo.toml
- examples/image_viewer.rs
- examples/image_viewporter.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- src/compositor.rs
- src/error.rs
- src/output.rs
- src/registry.rs
- src/seat/keyboard/mod.rs
- src/seat/mod.rs
- src/seat/touch.rs
- src/shell/layer/mod.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/popup.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
- src/shm/mod.rs
- src/shm/multi.rs
- src/shm/raw.rs
- src/shm/slot.rs
This is the SCTK side of https://github.com/Smithay/wayland-rs/pull/531 and https://github.com/Smithay/wayland-rs/pull/530 - it moves failures out of the `Arc::new_cyclic` closure, removing the need for the `Option` there.
> Updates for infallible creation methods

- examples/list_outputs.rs
- src/output.rs
The documentation for `wl_output::mode` and `wl_output::geometry` specifically states to use the information from these `xdg_output` events for "logical" size and position within the "global compositor space". Which may be impacted by scaling and transform. Given this, the properties are not redundant and should be handled.
Testing under Sway, and looking at the implementation of wlroots, `x` and `y` in the `geometry` event are always given as `0`, but the `logical_position` has useful values.
> outputs: Add `logical_position` and `logical_size` properties

- src/seat/keyboard/mod.rs
This is meant to provide a way to address
https://github.com/pop-os/xdg-shell-wrapper/issues/8, in combination with https://github.com/Smithay/smithay/pull/750.
This is currently potentially unsound due to the
`unsafe impl Send for KeyboardData {}`. `xdg::Keymap` uses non-thread-safe ref-counting, but sctk assumes it is only used from one thread. This is difficult to address.
> Add `update_keymap` method that's called when server provides keymap

- examples/generic_list_seats.rs
- examples/generic_simple_window.rs
- examples/image_viewer.rs
- examples/image_viewporter.rs
- examples/list_outputs.rs
- examples/list_seats.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- examples/wgpu.rs
- src/output.rs
- src/registry.rs
- src/seat/mod.rs
This prevents the need to create two registry objects in examples like `simple_window`, and eliminates the need to manually implement `Dispatch`.
This would perhaps make it harder if an application wants to handle custom globals, instead of just putting that in the `Dispatch` implementation, but if the `RegistryState` helper doesn't already provide an ergonomic way to do that, maybe the way the `ProvidesRegistryState` trait and `registry_handlers!` macro work isn't ideal?
Leaving as a draft because I think it might be good to remove `ready()` and make things like `OutputState::new()` also take a `&GlobalList`. But does this seem like a generally good approach?
> Make `RegistryState` depend on use of `registry_queue_init`

- Cargo.toml
`calloop` depends on 0.25, so this avoid having two versions in the dependency tree.
> Update nix to 0.25

- src/output.rs
Currently, xdg-output-manager is bound during OutputState creation unconditionally, so there is no need to check it.
Please correct me if I'm wrong.
> remove unnecessary code that lazily binds xdg-output-manager

- src/seat/mod.rs
- src/seat/pointer/mod.rs
The mut was basically never used.
> seat: remove mut from `ThemedPointer::set_cursor`

- src/output.rs
The `OutputInfo` is already stored in the data, so this commit makes access to it.
--
I think it's a leftover that it wasn't ported.
> output: add `OutputData::with_output_info`

- src/seat/pointer/mod.rs
This should help when using custom cursor images or trying to hide the cursor.
> pointer: add a way to access the latest_enter_serial

- src/seat/keyboard/repeat.rs
This will ensure that our time computations are all sane and remove C like random unsigned additions.
> keyboard: use typesafe wrappers for gap and delay

- src/seat/keyboard/mod.rs
- src/seat/keyboard/repeat.rs
The modifiers state wasn't re-broadcasted when nothing got changed in the effective state, which was incorrect for multi-window clients, since it may spawn new window with depressed modifiers resulting in new windows not seeing modifiers update event.
This commit also fixes the issue when key repeating stops due to pressing SHIFT, while it should just alter the key and 'keep' the repeat going.
> keyboard: fix modifiers on re-issue and repeat

- src/seat/mod.rs
- src/seat/pointer/mod.rs
The `ThemedPointer` always assumed that it's being used with the `PointerData` leading to issues when used with custom udata.
--
Not sure if that's an ideal solution, maybe you can somehow avoid generic param all-together.
> seat/pointer: fix `ThemedPointer::set_cursor` udata

- src/error.rs
- src/registry.rs
This doesn't seem to serve any role after https://github.com/Smithay/client-toolkit/pull/313.
> Remove `GlobalProxy::NotReady` variant

- examples/relative_pointer.rs
- src/seat/mod.rs
- src/seat/relative_pointer.rs
In a future PR adding pointer constraints, the example could be updated to demonstrate relative motion in combination with pointer locks and confinement. But here it just prints motion events a window receives.
> Add relative pointer, and an example using it

- src/seat/keyboard/mod.rs
- src/seat/keyboard/repeat.rs
- src/seat/mod.rs
- src/seat/pointer/mod.rs
- src/seat/touch.rs
This should help with handling of multi-seat given that all input must be associated with the seat, but right now it'll require manually finding the right seat on each input of the event.
> seat: store seat in udata

- examples/pointer_theme_window.rs
- src/seat/mod.rs
The `WlPointer` is already stored on the `ThemedPointer`, so you can get it from it without the need to return a tuple of `(WlPointer, ThemedPointer)`.
> seat: return just `ThemedPointer` when creating it

- examples/pointer_theme_window.rs
- src/seat/mod.rs
- src/seat/pointer/mod.rs
Previous API flow was to recreate a `ThemedPointer` each time you want to change scale, which is counterintuitive, given that the inner wl_pointer, shouldn't be dropped.
> seat: explicitly pass scale each time for pointer

- Cargo.toml
- examples/relative_pointer.rs
- src/seat/mod.rs
- src/seat/pointer_constraints.rs
This needs documentation, and the example can be updated to demonstrate its usage.
Not sure if we can provide any useful higher-level API over `ZwpConfinedPointerV1` and `ZwpLockedPointerV1`. I don't think it's possible to provide an API that can't produce protocol errors at the level sctk operates.
> Add bindings for pointer constraints 

- Cargo.toml
Looks like the fix for this is in `wayland-client` 0.30.1 now.
> Remove workaround depending on `wayland-client/log`

- Cargo.toml
- build.rs
--
Not sure whether the `dlopen` is needed for `xkbcommon`, but I can say for sure that it's not used right now. This commit should fix the build failure when libxkbcommon-dev is not present on the system.
> build: don't look for libxkbcommon without feature

- examples/generic_simple_window.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
This should simplify handling and storing the state downstream.
> window: use bitflags for window state

- src/shell/xdg/window/mod.rs
Raw identifiers are really only meant for cases where it's technically necessary to use a particular identifier (like when a keyword was added by an edition, but an API currently uses that as an identifier).
I this an `_` suffix is the most idiomatic solution.
> Don't use raw identifier in method name

- examples/generic_simple_window.rs
- examples/image_viewer.rs
- examples/image_viewporter.rs
- examples/pointer_theme_window.rs
- examples/relative_pointer.rs
- examples/simple_window.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/inner.rs
- src/shell/xdg/window/mod.rs
The protocol states:
>If the width or height arguments are zero, it means the client should
>decide its own window dimension.
Meaning that either could be zero, though it's not clear whether all dimensions should be picked, or just the one with zero.
It was also observed in the wild that some compositors could send negative values for the configure, in which we should protect and pick our own sizes to not cause overflow on casting.
--
We could rollback to tuple and then if some of them is zero, meaning that both dimensions should be picked.
> window: use NonZeroU32 for WindowConfigure::new_size

- examples/themed_window.rs
- src/compositor.rs
- src/lib.rs
- src/shell/xdg/frame/fallback_frame.rs
- src/shell/xdg/frame/mod.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/window/mod.rs
- src/subcompositor.rs
While the new decorations look the same as the ones before, the
approach in drawing them was changed, and now decorations are more
instant mode, meaning that you create and drop them when needed.
Fixes #273.
--
This series also adds subcompositor and subsurface handlers. The parent surface stuff is
intended to be used from inside winit, yet, I haven't added it into it.
The example which is using CSD decorations is `themed_window`.
All the drawing was ported from before.
cc @PolyMeilex
> window: add client side decorations interface

- examples/wgpu.rs
Looks like https://github.com/Smithay/client-toolkit/pull/322 broke this.
I guess the other examples are tested on CI but this one isn't since it requires `--features="wayland-backend/client_system"`?
> Fix wgpu example

- CHANGELOG.md
- Cargo.toml
- examples/themed_window.rs
- src/seat/mod.rs
- src/seat/pointer/mod.rs
- src/shell/xdg/frame/fallback_frame.rs
- src/shell/xdg/frame/mod.rs
This should simplify the handling of custom cursors in the user applications by incapsulating all the necessary state in the ThemedPointer.
In the future we can automatically handle the `wp_cursor_shape` under the hood.
> seat/pointer: simplify ThemedPointer handling

- Cargo.toml
Not sure when this happened, but apparently the `lazy_static` dependency is entirely unused.
Would play nice with https://github.com/Smithay/wayland-rs/pull/627.
> Remove unused `lazy_static` dependency

- CHANGELOG.md
- src/data_device_manager/mod.rs
The `DataDeviceManagerState` API was restricted to `&str` while it was simply calling `to_string` on each element of the iterator, so make the iterator use `ToString`.
> data_device: use `T: ToString` for mimes iterator

- CHANGELOG.md
- examples/data_device.rs
- src/lib.rs
- src/primary_selection/device.rs
- src/primary_selection/mod.rs
- src/primary_selection/offer.rs
- src/primary_selection/selection.rs
Add support for the zwp_primary_selection_v1 protocol. The implementation is similar to the existing data_device protocol, however much simpler, given that there's no drag and drop.
The data_device example was abused to show the primary selection in use.
> api: add zwp_primary_selection_v1 support

- src/environment.rs
This is a partial fix for the way SimpleGlobal binds to the latest version offered by the server instead of the latest version the client understands, which causes errors (usually leading to crashes) when a server actually uses the later version and sends an event we don't know about.
This fixes crashes in a number of clients using SCTK-0.16 on compositors supporting the newest wayland surface APIs (to be precise, any that send a `preferred_buffer_scale` event).
> Restrict SimpleGlobal bindings to our max API version

- .github/workflows/ci.yml
- README.md
Update the MSRV following the windowing ecosystem bump in the MSRV.
> Bump MSRV to 1.65

- CHANGELOG.md
- Cargo.toml
- examples/data_device.rs
- examples/simple_window.rs
- src/compositor.rs
- src/data_device_manager/data_offer.rs
- src/data_device_manager/read_pipe.rs
- src/data_device_manager/write_pipe.rs
- src/lib.rs
- src/primary_selection/offer.rs
- src/shell/wlr_layer/mod.rs
- src/shell/xdg/mod.rs
- src/shm/multi.rs
- src/shm/raw.rs
- src/shm/slot.rs
Suggested-by: Ian Douglas Scott <idscott@system76.com>
Fixes #402.
Based on #403, cc @ids1024 @DjMcNab
The calloop wayland source doesn't work and not released yet. https://github.com/Smithay/calloop-wayland-source/pull/1
> Update calloop and wayland-rs to the latest versions

- CHANGELOG.md
- src/data_device_manager/data_offer.rs
- src/primary_selection/offer.rs
This appears to be the only use of `RawFd` in a public API. With this change, these functions should be safe to call.
I'm not sure if it would make more sense for these functions to not close the file descriptor. In which case they could take `BorrowedFd`. But this matches the current implementation, but with an IO safe type.
> Take `OwnedFd` instead of `RawFd` as argument to `receive_to_fd`

- examples/data_device.rs
- src/data_device_manager/data_device.rs
- src/data_device_manager/data_offer.rs
While the spec says to destroy the wl_data_offer after wl_data_device::leave, I think compositors often send the leave event right away after a drop. This is a bit problematic if an application hasn't finished receiving the data and then the data offer is destroyed before it can make the finish request. I believe this can currently be recreated in the data_device example. The source never receives a finish event because the offer was destroyed and isn't alive by the time we make the request.
This PR tries to avoid destroying an offer after the leave event if a drop event already occurred. It also tries to avoid making request besides finish or destroy.
> fix(wl_data_device): drop and leave event handling

- Cargo.toml
- src/data_device_manager/data_offer.rs
- src/primary_selection/offer.rs
- src/shm/mod.rs
- src/shm/raw.rs
This is cleaner than `nix` due to the use of `OwnedFd`/`BorrowedFd`.
`calloop` is already using `rustix`.
Depends on https://github.com/bytecodealliance/rustix/pull/848.
> Use `rustix` instead of `nix`

- src/seat/keyboard/mod.rs
`strace ./target/debug/examples/simple_window 2>&1| grep EBADF` shows this error before this change.
`new_from_fd` calls `File::from` on the fd, which results in closing it on drop.
> Fix double `close` when calling `xkb::Keymap::new_from_fd`

- Cargo.toml
- examples/dmabuf_formats.rs
- src/dmabuf.rs
- src/lib.rs
An implementation of this protocol is useful with the screencopy protocol.
The implementation here is incomplete, in particular the dmabuf feedback code. Only implementing version 3, without that makes this simpler, but presumably that mechanism is useful if complicated where supported by the compositor.
> `zwp_linux_dmabuf_v1` protocol

- examples/data_device.rs
- src/data_device_manager/read_pipe.rs
- src/data_device_manager/write_pipe.rs
- src/primary_selection/offer.rs
This should simplify client handling, since they can properly model the read/write loop.
> data_device: return `PostAction` for the Read/Write pipe

- Cargo.toml
> chore: drop dlib dependency

- examples/session_lock.rs
- src/lib.rs
- src/session_lock/dispatch.rs
- src/session_lock/mod.rs
- src/shell/wlr_layer/mod.rs
- src/shell/xdg/mod.rs
I modelled the API here on how layer shell is handled.
`SessionLock` and `SessionLockSurface` destroy their corresponding Wayland objects on drop. In the case of `SessionLock`, it is incorrect to do this before `locked`/`finished` are received, but also incorrect to not destroy it. For security, the compositor remains locked if any of these things are done incorrectly.
Ideally `SessionLock` then might be a linear type that you can't drop but have to pass to an explicit destroy function, but in lieu of such functionality, it's marked `#[must_use]`.
The example simply creates a lock, creates a lock surface for each output with the same colorful graphic as `simple_window`, and terminates after 5 seconds.
> Add session-lock protocol

- src/compositor.rs
- src/shell/xdg/mod.rs
- src/shell/xdg/popup.rs
Two recent bumps to maximum API versions did not also bump the implementations of ProvidesBoundGlobal even though API breaks were present.  This series bumps those API versions.  This is technically an API change, albeit a minor one that would only break code directly using the ProvidesBoundGlobal interface on one of these objects - and such code may already be broken in 0.18 because it will not handle the new events.
> ProvidesBoundGlobal API_VERSION fixes

- examples/simple_window.rs
- src/activation.rs
- src/lib.rs
Implements xdg-activation.
The second commit adds it to the simple-window example as a test. Given how heavily commented that is, I guess that is not really a good place to put it. But without a proper window it doesn't make a whole lot of sense to use it. I could also just drop that commit?
> Implement support for xdg-activation

- Cargo.toml
- src/seat/pointer/mod.rs
Try the standardized cursor icon name, followed by a list of alternative cursor icon names (provided through https://github.com/rust-windowing/cursor-icon/pull/11).
See also:
- https://github.com/Smithay/client-toolkit/issues/425
- https://github.com/rust-windowing/cursor-icon/pull/11
cc @kchibisov 
Fixes #425
> Try alternative cursor icon names

- src/shm/multi.rs
PoolError::Overlap is returned when the buffer is bigger than the slot and not the other way around.
> fix: MultiPool::get now returns an overlap error when its appropriate

- examples/session_lock.rs
- src/session_lock/mod.rs
The entire reason unlock_and_destroy is distinct from destroy is to avoid accidental unlock operations.  The current SCTK implementation carefully undoes this work by unlocking on drop, even if that drop is due to a panic or careless drop of the lock object.
Add an explicit unlock call so that screen lockers can indicate when they intend to unlock (generally after some kind of authentication has happened).
> Require an explicit unlock call in SessionLock

- src/seat/touch.rs
Weston <= 10 at least has a bug where the frame event isn't always sent when the last touch point was released.
This is tracked in
https://gitlab.freedesktop.org/wayland/weston/-/issues/44 and it would seem that
https://gitlab.freedesktop.org/wayland/weston/-/commit/5448580111b5ff992ce2603cb6e99b9f54db7ad8 may fix it.
Meanwhile, work around the issue by processing all buffered events when there are no more active touch points.
> Work around touch up events delivered too late with certain Weston versions

- Cargo.toml
- examples/dmabuf_formats.rs
- src/dmabuf.rs
This makes creating a dmabuf with different modifiers for different planes a protocol error.
This *could* be considered a breaking API change, but I don't think we need a semver bump for it because:
* Callers should never have actually used different modifiers for different planes, since this was never valid.
* Most users of this protocol tend to use `create_immed`, in which case they would get a protocol error. So it's "breaking" only if an application calls `create` with non-sense params and then expects to get `failed`.
When we do have an API break, the API should probably be changed to only allow a single modifier.
This change isn't important, but will be needed for future updates to dmabuf.
> Bind dmabuf v5

- .github/workflows/ci.yml
This could help fix CI issues on some PRs like #441 and #437
> chore: refactor github ci so that it doesn't use 1.65 for tests

- src/seat/pointer/mod.rs
- src/seat/touch.rs
This is needed to call things like `xdg_toplevel::move` for touch events.
> seat/touch: Track latest `touch_down` event serial

- src/subcompositor.rs
I'd like to be able to pass an existing surface and make it a subsurface, instead of using the surface created in `create_subsurface`.  Would that be possible with something like this?   Thanks :)
> add way to make subsurfaces from surfaces

- CHANGELOG.md
- examples/data_device.rs
- examples/generic_simple_window.rs
- examples/image_viewer.rs
- examples/image_viewporter.rs
- examples/relative_pointer.rs
- examples/session_lock.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- examples/themed_window.rs
- src/compositor.rs
While the `outputs()` method on `SurfaceData` allows an app to retrieve the *current* outputs of a surface, it's not currently possible to easily *detect changes* to this value.
This pull-request adds the `surface_enter`/`surface_leave`  methods to the `CompositorHandler` trait. These methods correspond to the [`wl_surface::enter`](https://wayland.app/protocols/wayland#wl_surface:event:enter)/[`wl_surface::leave`](https://wayland.app/protocols/wayland#wl_surface:event:leave) events and should make it easier for client apps to detect  changes to a surface's outputs.
> [!NOTE] 
> See https://github.com/vially/flutter-rs/commit/03ff77836c12e0092b6a46f7445013f9a48c1035 for a more realistic use-case of these methods.
> Add `surface_enter`/`surface_leave` methods to `CompositorHandler`

- Cargo.toml
Depends on https://github.com/Smithay/calloop-wayland-source/pull/4.
I guess this will be a breaking change... hopefully `calloop` can be more stable now.
> Update `calloop` to `0.14.0`, `calloop-wayland-source`

- examples/session_lock.rs
The example would previously show a solid color for 1.5s, after which the lock surfaces were created. With multiple displays, the surfaces would sometimes not be created at all.
The issue here is that the compositor expects a surface to be created for each display before `locked` is called, and since the example only creates the surfaces in `locked` the compositor would time out waiting for the surfaces, resulting in the placeholder solid color screen.
I've also added some more comments, clarifying some things that I ran into while trying to use the protocol myself.
Lastly, I've changed the `finished` log, since from my understanding, `finished` is only called if the session failed to be locked, and will not be called if the session is locked and unlocked normally.
> fix: Fix session lock example and add more explanations

- examples/foreign-toplevel-monitor.rs
- src/foreign_toplevel_list.rs
- src/lib.rs
Provides a handler API similar to the output API.
> Add `ext-foreign-toplevel-list-v1` protocol

- Cargo.toml
- examples/wgpu.rs
Hello, recently had to reference wgpu example and noticed that it does not implement `surface_enter` and `surface_leave` that are required by CompositorHandler.
> Fix wgpu example by adding new CompositorHandler implimentations

- src/dmabuf.rs
- src/globals.rs
The `DmabufHandler::dmabuf_feedback` handler provides access to DMA buffer feedback, however working with this feedback becomes difficult when it needs to be stored in multiple places due to missing derives.
So this patch adds the automatic `Clone` derive so the existing types in SCTK can be reused downstream.
The `DmabufFeedback` itself does not implement `Clones` since it relies on the `Mmap` type, which is not cloneable.
---
Note I didn't actually require this myself since I was able to clone the WebKit type I used it for. But it seems useful for other people so I thought I might as well put up a PR.
> Add Clone for dmabuf feedback structs

- src/lib.rs
- src/presentation_time.rs
A fairly simple protocol (that basically amounts to a single function returning a future, functionally?). But a couple small things are a bit awkward here.
Also needs example and basic docs.
> Add `wp_presentation` protocol

- examples/data_device.rs
- examples/generic_simple_window.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- examples/themed_window.rs
- src/seat/keyboard/mod.rs
This can be used for things like nested compositors, that want to propagate the modifier state as expressed by the compositor.
> Add a `raw_modifiers` argument to `update_modifiers`

- src/shm/raw.rs
Makes sense to provide alongside `Write` and `Seek`, and useful for using shm buffers with other protocols like Pipewire.
`SlotPool` can't provide this, as a safe accessor.
> Implement `AsFd` for `RawPool`

- src/registry.rs
This seems a bit more convenient than defining a type and manually implementing `ProvidesBoundGlobal`.
(I wonder if the API of `ProvidesBoundGlobal` and such could be improved, but this fits with what's already present.)
> Add `SimpleGlobal::from_bound` method to construct from proxy object

- examples/simple_layer.rs
The `wlr-layer-shell-unstable` protocol says:
> If the width or height arguments are zero, it means the client should decide its own window dimension.
While the wording doesn't make it clear, I think it's reasonable to assume it's talking about each dimension *separately* - the word "dimension" isn't plural, and there's legitimate use cases for this behavior (e.g. scrolling compositors like niri).
Relevent issue: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/155 (about xdg-shell not layer-shell, the wording comes from there)
This can also be written as:
```rs
self.width = Some(configure.new_size.0).filter(|width| *width != 0).unwrap_or(256);
self.height = Some(configure.new_size.1).filter(|height| *height != 0).unwrap_or(256);
```
or plain ifs, which might be a little …
> simple_layer example: Handle 0 width/height in configure correctly

- Cargo.toml
There doesn’t appear to be any kind of changelog or release notes available for `xkbcommon`, but the full source diff is:
https://github.com/rust-x-bindings/xkbcommon-rs/compare/v0.7.0...v0.8.0
Commit messages indicate that this update contains some bug fixes.
It looks like the SemVer-incompatible change was to the value of the string `MOD_NAME_MOD3`, which is in the public API: https://github.com/rust-x-bindings/xkbcommon-rs/commit/f799423877d345a04a58727a59ab4a38658f89ba. I think that shouldn’t require any code changes in `client-toolkit`.
I confirmed that `cargo test` still passes.
> Update xkbcommon to 0.8

- .github/workflows/ci.yml
This should fix the [currently broken](https://github.com/Smithay/client-toolkit/actions/runs/14986221417/job/42100552606) `lint` stage of the CI
> ci: Update hecrj/setup-rust-action to v2

- Cargo.toml
- src/lib.rs
- src/seat/input_method.rs
- src/seat/mod.rs
Only the input-method object is supported. No keyboard grab, no popup surface.
This is already useful.
Client demo: https://codeberg.org/dcz/stiwri
The client only does a couple canned requests, but it shows:
- looking at preedit (command line)
- submitting text (button)
- showing preedit (buttons)
which is most of the functionality here.
> Partially add zwp-input-method-v2

- Cargo.toml
- src/shm/raw.rs
the only thing that i had to adjust for with the rustix update is the rename of `rustix::shm::shm_open` to just `rustix::shm::open` (and the same with `the `ShmOflags` and `shm_unlink`), everything else seems to have stayed compatible.
i didn't need to change anything for the thiserror update.
> update to rustix 1 and thiserror 2

- examples/data_device.rs
- examples/generic_simple_window.rs
- examples/simple_layer.rs
- examples/simple_window.rs
- examples/themed_window.rs
- src/seat/keyboard/mod.rs
- src/seat/mod.rs
This adds a new method repeat_key for the keys that come with the repeated mark.
> wl_keyboard: Add support for repeating from v10

- Cargo.toml
- src/lib.rs
- src/seat/input_method_v3.rs
- src/seat/mod.rs
With popup additions: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/407
Missing/untested: repositioning.
> Implement experimental input method protocol
